IceCreamShop/force-app/main/default/objects/Ice_Cream_Flavor__c/Ice_Cream_Flavor__c.object-meta.xml
<CustomObject>
    <label>Ice Cream Flavor</label>
    <nameField>
        <label>Ice Cream Flavor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ice Cream Flavors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

IceCreamShop/force-app/main/default/objects/Ice_Cream_Flavor__c/fields/Color__c.field-meta.xml
<CustomField>
    <fullName>Color__c</fullName>
    <description>The color used on the Flavors web page.  Like &quot;green&quot; or like &quot;#ab1231&quot;.</description>
    <label>Color</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

IceCreamShop/force-app/main/default/objects/Ice_Cream_Flavor__c/fields/Sale_Price_Per_Scoop__c.field-meta.xml
<CustomField>
    <fullName>Sale_Price_Per_Scoop__c</fullName>
    <label>Sale Price Per Scoop</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

IceCreamShop/force-app/main/default/objects/Sale__c/Sale__c.object-meta.xml
<CustomObject>
    <label>Sale</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Sale Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

IceCreamShop/force-app/main/default/objects/Sale__c/fields/Ice_Cream_Flavor__c.field-meta.xml
<CustomField>
    <fullName>Ice_Cream_Flavor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Ice Cream Flavor</label>
    <referenceTo>Ice_Cream_Flavor__c</referenceTo>
    <relationshipLabel>Sales</relationshipLabel>
    <relationshipName>Sales</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

IceCreamShop/force-app/main/default/objects/Sale__c/fields/Scoop_Number__c.field-meta.xml
<CustomField>
    <fullName>Scoop_Number__c</fullName>
    <label>Scoop Number</label>
    <precision>1</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

IceCreamShop/force-app/main/default/classes/FlavorPageController.cls
public class FlavorPageController {

    public List<Ice_Cream_Flavor__c> allFlavors {get; set;}
    public List<PopularFlavorWrapper> flavorWrappers {get;set;}
    
    public FlavorPageController() {
        allFlavors = [SELECT Id, Name, Sale_Price_Per_Scoop__c, Color__c FROM Ice_Cream_Flavor__c ORDER BY Name];
        System.debug('All flavors' + allFlavors);
        
        Map<Id, Ice_Cream_Flavor__c> flavorIDMap = new Map<Id, Ice_Cream_Flavor__c>(allFlavors);
        
        List<AggregateResult> mostPopular = [SELECT Ice_Cream_Flavor__r.Id, SUM(Scoop_Number__c)
                                             FROM Sale__c GROUP BY Ice_Cream_Flavor__r.Id
                                            ORDER BY SUM(Scoop_Number__c) DESC LIMIT 3];
        
        flavorWrappers = new List<PopularFlavorWrapper>();
        for (AggregateResult ar : mostPopular) {
            PopularFlavorWrapper wrapper = new PopularFlavorWrapper();
            wrapper.flavor = flavorIDMap.get(ar.Id);
            wrapper.numberSold = Integer.valueOf((Decimal)ar.get('expr0'));
            flavorWrappers.add(wrapper);
        }
        System.debug('Most popular' + mostPopular);
        System.debug('FLavor wrappers' + flavorWrappers);
    }
}