IceCreamShop/force-app/main/default/objects/Ice_Cream_Flavor__c/Ice_Cream_Flavor__c.object-meta.xml
<CustomObject>
    <label>Ice Cream Flavor</label>
    <nameField>
        <label>Ice Cream Flavor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ice Cream Flavors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

IceCreamShop/force-app/main/default/objects/Ice_Cream_Flavor__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

IceCreamShop/force-app/main/default/objects/Inventory__c/Inventory__c.object-meta.xml
<CustomObject>
    <label>Inventory</label>
    <nameField>
        <label>Inventory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventory</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

IceCreamShop/force-app/main/default/objects/Inventory__c/fields/Ice_Cream_Flavor__c.field-meta.xml
<CustomField>
    <fullName>Ice_Cream_Flavor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ice Cream Flavor</label>
    <referenceTo>Ice_Cream_Flavor__c</referenceTo>
    <relationshipLabel>Inventory</relationshipLabel>
    <relationshipName>Inventory</relationshipName>
    <type>Lookup</type>
</CustomField>

IceCreamShop/force-app/main/default/objects/Inventory__c/fields/Is_Ice_Cream__c.field-meta.xml
<CustomField>
    <fullName>Is_Ice_Cream__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Ice Cream</label>
    <type>Checkbox</type>
</CustomField>

IceCreamShop/force-app/main/default/classes/UpdateIceCreamFromInventory.cls
public class UpdateIceCreamFromInventory {

    public void updateIceCreamQuantity(List<Inventory__c> inventoryList){
           
        //check box to see if it is ice cream or not.
    	if(inventoryList[0].Is_Ice_Cream__c){
        
        	//SOQL Query to retrieve flavor for update
			List <Ice_Cream_Flavor__c> flavorList = [SELECT Id, Quantity__c, Name FROM Ice_Cream_Flavor__c  
                                             		WHERE Id =: inventoryList[0].Ice_Cream_Flavor__c]; 

            //increase quantity of the ice cream buckets, based on new inventory. 
        	flavorList[0].Quantity__c = ( inventoryList[0].Quantity__c + flavorList[0].Quantity__c );
        
            //updates the Ice_Cream_Flavors_c object. 
        	update flavorList; 

    	}
    }
}