IceCreamShop/force-app/main/default/objects/Ice_Cream_Flavor__c/Ice_Cream_Flavor__c.object-meta.xml
<CustomObject>
    <label>Ice Cream Flavor</label>
    <nameField>
        <label>Ice Cream Flavor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ice Cream Flavors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

IceCreamShop/force-app/main/default/objects/Ice_Cream_Flavor__c/fields/Current_Scoops_Removed__c.field-meta.xml
<CustomField>
    <fullName>Current_Scoops_Removed__c</fullName>
    <label>Current Scoops Removed</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

IceCreamShop/force-app/main/default/objects/Ice_Cream_Flavor__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

IceCreamShop/force-app/main/default/objects/Sale__c/Sale__c.object-meta.xml
<CustomObject>
    <label>Sale</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Sale Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

IceCreamShop/force-app/main/default/objects/Sale__c/fields/Ice_Cream_Flavor__c.field-meta.xml
<CustomField>
    <fullName>Ice_Cream_Flavor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Ice Cream Flavor</label>
    <referenceTo>Ice_Cream_Flavor__c</referenceTo>
    <relationshipLabel>Sales</relationshipLabel>
    <relationshipName>Sales</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

IceCreamShop/force-app/main/default/objects/Sale__c/fields/Scoop_Number__c.field-meta.xml
<CustomField>
    <fullName>Scoop_Number__c</fullName>
    <label>Scoop Number</label>
    <precision>1</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

IceCreamShop/force-app/main/default/classes/ScoopReducesQuantity.cls
public class ScoopReducesQuantity {
    
	public void scoopCheck(List <Sale__c> sale){
        
        //SOQL Query to retrieve current scoops, scooped
		List <Ice_Cream_Flavor__c> flavorList = [SELECT Id, Current_Scoops_Removed__c, Quantity__c FROM Ice_Cream_Flavor__c  
                                             	WHERE Id =: sale[0].Ice_Cream_Flavor__c];     
            
            //Little buckets of ice cream, only hold 10 scoops each. 
            if( ( flavorList[0].Current_Scoops_Removed__c + sale[0].Scoop_Number__c ) >= 9 ){
                
                Integer extraScoops = 0; 
               
                if (flavorList[0].Current_Scoops_Removed__c + sale[0].Scoop_Number__c > 9){
                    extraScoops = (Integer)(flavorList[0].Current_Scoops_Removed__c + sale[0].Scoop_Number__c - 9);
                }else{
                    extraScoops = (Integer)sale[0].Scoop_Number__c; 
                }
                
                flavorList[0].Current_Scoops_Removed__c = extraScoops;
                flavorList[0].Quantity__c = ( flavorList[0].Quantity__c - 1 ); 
            }
    	update flavorList; 
    }
}