IceCreamShop/force-app/main/default/objects/Ice_Cream_Flavor__c/Ice_Cream_Flavor__c.object-meta.xml
<CustomObject>
    <label>Ice Cream Flavor</label>
    <nameField>
        <label>Ice Cream Flavor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ice Cream Flavors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

IceCreamShop/force-app/main/default/objects/Ice_Cream_Flavor__c/fields/Current_Scoops_Removed__c.field-meta.xml
<CustomField>
    <fullName>Current_Scoops_Removed__c</fullName>
    <label>Current Scoops Removed</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

IceCreamShop/force-app/main/default/objects/Ice_Cream_Flavor__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

IceCreamShop/force-app/main/default/objects/Ice_Cream_Flavor__c/fields/Sale_Price_Per_Scoop__c.field-meta.xml
<CustomField>
    <fullName>Sale_Price_Per_Scoop__c</fullName>
    <label>Sale Price Per Scoop</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

IceCreamShop/force-app/main/default/objects/Inventory__c/Inventory__c.object-meta.xml
<CustomObject>
    <label>Inventory</label>
    <nameField>
        <label>Inventory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventory</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

IceCreamShop/force-app/main/default/objects/Inventory__c/fields/Ice_Cream_Flavor__c.field-meta.xml
<CustomField>
    <fullName>Ice_Cream_Flavor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ice Cream Flavor</label>
    <referenceTo>Ice_Cream_Flavor__c</referenceTo>
    <relationshipLabel>Inventory</relationshipLabel>
    <relationshipName>Inventory</relationshipName>
    <type>Lookup</type>
</CustomField>

IceCreamShop/force-app/main/default/objects/Inventory__c/fields/Is_Ice_Cream__c.field-meta.xml
<CustomField>
    <fullName>Is_Ice_Cream__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Ice Cream</label>
    <type>Checkbox</type>
</CustomField>

IceCreamShop/force-app/main/default/objects/Sale__c/Sale__c.object-meta.xml
<CustomObject>
    <label>Sale</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Sale Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

IceCreamShop/force-app/main/default/objects/Sale__c/fields/Amount_Due__c.field-meta.xml
<CustomField>
    <fullName>Amount_Due__c</fullName>
    <label>Amount Due</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

IceCreamShop/force-app/main/default/objects/Sale__c/fields/Ice_Cream_Flavor__c.field-meta.xml
<CustomField>
    <fullName>Ice_Cream_Flavor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Ice Cream Flavor</label>
    <referenceTo>Ice_Cream_Flavor__c</referenceTo>
    <relationshipLabel>Sales</relationshipLabel>
    <relationshipName>Sales</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

IceCreamShop/force-app/main/default/objects/Sale__c/fields/Scoop_Number__c.field-meta.xml
<CustomField>
    <fullName>Scoop_Number__c</fullName>
    <label>Scoop Number</label>
    <precision>1</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

IceCreamShop/force-app/main/default/classes/TestClass.cls
@isTest (SeeAllData=true)
public class TestClass {
    
    @isTest
    static void testSalePriceCaculator(){

        List <Sale__c> sale = new List <Sale__c>(); 
        List <Ice_Cream_Flavor__c> flavorList = [SELECT Id, Sale_Price_Per_Scoop__c, Quantity__c 
                                                 FROM Ice_Cream_Flavor__c  LIMIT 1];
        
        //set up new sales obj
        sale.add(new Sale__c());
        sale[0].Ice_Cream_Flavor__c = flavorList[0].Id;
        sale[0].Scoop_Number__c = 9; 
        
        //set up flavor list
        flavorList[0].Current_Scoops_Removed__c = 0; 
        flavorList[0].Quantity__c = 5;
        
        update flavorList; 
        insert sale; 

        Integer quantityExpected = (Integer)(flavorList[0].Quantity__c - 1);

        List <Sale__c> sale2 = [SELECT Id, Amount_Due__c, Ice_Cream_Flavor__c FROM Sale__c WHERE Id =: sale[0].Id];
        
        List <Ice_Cream_Flavor__c> flavorList2 = [SELECT Id, Quantity__c FROM Ice_Cream_Flavor__c  
                                             	 WHERE Id =: sale2[0].Ice_Cream_Flavor__c];
		
        //Check CaculateSalesPriceForTrigger/ calculatePrice
        System.assertEquals( (sale[0].Scoop_Number__c 
                             * flavorList[0].Sale_Price_Per_Scoop__c), 
                            sale2[0].Amount_Due__c); 
        
        //Check ScoopReducesQuantity/ scoopCheck
        System.assertEquals(quantityExpected, flavorList2[0].Quantity__c);    
    }
    
    @isTest
    static void testUpdateIceCreamViaInventoryTrigger(){
        
        List<Inventory__c> inventoryList = new List <Inventory__c>();
        inventoryList.add(new Inventory__c()); 
        
        List <Ice_Cream_Flavor__c> flavorList = [SELECT Id, Quantity__c, Name FROM Ice_Cream_Flavor__c LIMIT 1]; 

        inventoryList[0].Quantity__c = 3;
        inventoryList[0].Is_Ice_Cream__c = true; 
        inventoryList[0].Ice_Cream_Flavor__c = flavorList[0].Id;
        
        Integer total = (Integer)(flavorList[0].Quantity__c + inventoryList[0].Quantity__c);

        insert inventoryList; //trigger test
        
        List <Ice_Cream_Flavor__c> flavorList2 = [SELECT Id, Quantity__c, Name FROM Ice_Cream_Flavor__c  
                                             		WHERE Id =: inventoryList[0].Ice_Cream_Flavor__c]; 
        
        Integer sum = (Integer)(flavorList[0].Quantity__c + inventoryList[0].Quantity__c);
        System.assertEquals(sum, flavorList2[0].Quantity__c);               
    }
    
    
    @isTest
    static void testUpdateIceCreamFromInventory(){
        
        List<Inventory__c> inventoryList = [SELECT Is_Ice_Cream__c, Ice_Cream_Flavor__c, Quantity__c FROM Inventory__c];
        
        List <Ice_Cream_Flavor__c> flavorList = [SELECT Id, Quantity__c, Name FROM Ice_Cream_Flavor__c  
                                             		WHERE Id =: inventoryList[0].Ice_Cream_Flavor__c]; 
        flavorList[0].Quantity__c = 3;
        inventoryList[0].Quantity__c = 3;
        inventoryList[0].Is_Ice_Cream__c = true; 
        
        Integer total = (Integer)(flavorList[0].Quantity__c + inventoryList[0].Quantity__c);
        
        new UpdateIceCreamFromInventory().updateIceCreamQuantity(inventoryList); 
        
        List <Ice_Cream_Flavor__c> flavorList2 = [SELECT Id, Quantity__c, Name FROM Ice_Cream_Flavor__c  
                                             		WHERE Id =: inventoryList[0].Ice_Cream_Flavor__c]; 
        
        System.assertEquals(6, flavorList2[0].Quantity__c);                
    }
      
    @isTest
    static void testCaculateSalesPriceForTrigger(){

        List <Sale__c> sale = [SELECT Id, Scoop_Number__c, Amount_Due__c, Ice_Cream_Flavor__c FROM Sale__c];

        List <Ice_Cream_Flavor__c> flavorList = [SELECT Id, Sale_Price_Per_Scoop__c FROM Ice_Cream_Flavor__c  
                                             	 WHERE Id =: sale[0].Ice_Cream_Flavor__c];
  
        new CaculateSalesPriceForTrigger().calculatePrice(sale);
        
        System.assertEquals( (sale[0].Scoop_Number__c 
                             * flavorList[0].Sale_Price_Per_Scoop__c), 
                            sale[0].Amount_Due__c);    	
    }
    
    @isTest
    static void testScoopReducesQuantity(){

        List <Sale__c> sale = [SELECT Id, Scoop_Number__c, Amount_Due__c, Ice_Cream_Flavor__c FROM Sale__c LIMIT 1];

        //scoop resets at 9 
        sale[0].Scoop_Number__c = 9;
        
        List <Ice_Cream_Flavor__c> flavorList = [SELECT Id, Sale_Price_Per_Scoop__c, Name FROM Ice_Cream_Flavor__c  
                                             	 WHERE Id =: sale[0].Ice_Cream_Flavor__c];
        
        //set up flavor list
        flavorList[0].Current_Scoops_Removed__c = 0; 
        flavorList[0].Quantity__c = 5;
        update flavorList; 
        
        Integer quantityExpected = (Integer)(flavorList[0].Quantity__c - 1);
        
        Test.startTest();
    
        new ScoopReducesQuantity().scoopCheck(sale);
 
        Test.stopTest();
        
        //re-query for new values
        List <Ice_Cream_Flavor__c> flavorList2 = [SELECT Id, Quantity__c, Name FROM Ice_Cream_Flavor__c  
                                             	 WHERE Id =: sale[0].Ice_Cream_Flavor__c];
        
        System.assertEquals(quantityExpected, flavorList2[0].Quantity__c);
    }
}