IceCreamShop/force-app/main/default/objects/Ice_Cream_Flavor__c/Ice_Cream_Flavor__c.object-meta.xml
<CustomObject>
    <label>Ice Cream Flavor</label>
    <nameField>
        <label>Ice Cream Flavor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ice Cream Flavors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

IceCreamShop/force-app/main/default/objects/Ingredient__c/Ingredient__c.object-meta.xml
<CustomObject>
    <label>Ingredient</label>
    <nameField>
        <displayFormat>ICN-{0}</displayFormat>
        <label>Ice Cream Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ingredients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

IceCreamShop/force-app/main/default/objects/Ingredient__c/fields/Allergy__c.field-meta.xml
<CustomField>
    <fullName>Allergy__c</fullName>
    <label>Allergy</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Milk</fullName>
            </value>
            <value>
                <fullName>Gluten</fullName>
            </value>
            <value>
                <fullName>Tree Nuts</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

IceCreamShop/force-app/main/default/objects/Ingredient__c/fields/Calories__c.field-meta.xml
<CustomField>
    <fullName>Calories__c</fullName>
    <label>Calories</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

IceCreamShop/force-app/main/default/objects/Ingredient__c/fields/Carbs_g__c.field-meta.xml
<CustomField>
    <fullName>Carbs_g__c</fullName>
    <label>Carbs(g)</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

IceCreamShop/force-app/main/default/objects/Ingredient__c/fields/Cholesterol_mg__c.field-meta.xml
<CustomField>
    <fullName>Cholesterol_mg__c</fullName>
    <label>Cholesterol(mg)</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

IceCreamShop/force-app/main/default/objects/Ingredient__c/fields/Fat_g__c.field-meta.xml
<CustomField>
    <fullName>Fat_g__c</fullName>
    <label>Fat(g)</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

IceCreamShop/force-app/main/default/objects/Ingredient__c/fields/Ice_Cream_Flavor__c.field-meta.xml
<CustomField>
    <fullName>Ice_Cream_Flavor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Ice Cream Flavor</label>
    <referenceTo>Ice_Cream_Flavor__c</referenceTo>
    <relationshipLabel>Ingredients</relationshipLabel>
    <relationshipName>Ingredients</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

IceCreamShop/force-app/main/default/objects/Ingredient__c/fields/Pick_Ingredients__c.field-meta.xml
<CustomField>
    <fullName>Pick_Ingredients__c</fullName>
    <label>Pick Ingredients</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Blueberrys</fullName>
            </value>
            <value>
                <fullName>Cookie Dough</fullName>
            </value>
            <value>
                <fullName>Cream</fullName>
            </value>
            <value>
                <fullName>Flavoring</fullName>
            </value>
            <value>
                <fullName>Ice</fullName>
            </value>
            <value>
                <fullName>Milk</fullName>
            </value>
            <value>
                <fullName>Splenda</fullName>
            </value>
            <value>
                <fullName>Strawberries</fullName>
            </value>
            <value>
                <fullName>Sugar</fullName>
            </value>
            <value>
                <fullName>Vanilla</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

IceCreamShop/force-app/main/default/objects/Ingredient__c/fields/Protein_g__c.field-meta.xml
<CustomField>
    <fullName>Protein_g__c</fullName>
    <label>Protein(g)</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

IceCreamShop/force-app/main/default/objects/Ingredient__c/fields/Sugars_g__c.field-meta.xml
<CustomField>
    <fullName>Sugars_g__c</fullName>
    <label>Sugars(g)</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

IceCreamShop/force-app/main/default/objects/Ingredient__c/fields/TestField__c.field-meta.xml
<CustomField>
    <fullName>TestField__c</fullName>
    <label>TestField</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

IceCreamShop/force-app/main/default/classes/ControllerAllergy.cls
public class ControllerAllergy
{
    public List <Ice_Cream_Flavor__c> flavorList 
    {
        get 
        {
            if (flavorList != null)
            {
                return flavorList;
            }
            else
            {
                flavorList = [SELECT Id, Name FROM Ice_Cream_Flavor__c ];
                return flavorList;
            }
            
        }
        set;
    }

    public String name {get; set;}
    public Ingredient__c flavorIngredients {get; set;}

    //default constructor needed to extend standard controller. 
    public ControllerAllergy(ApexPages.StandardController controller){}

    public void flavorListClickHandlerApex()
    {
        this.flavorIngredients = [SELECT Ice_Cream_Flavor__r.Name, Name, Allergy__c, Pick_Ingredients__c 
                                  FROM Ingredient__c WHERE Ice_Cream_Flavor__r.Name LIKE :name LIMIT 1];
    }
    //hello
    @AuraEnabled
    public static Ingredient__c testString2(String search){
        String exampleString = search;
        //List<Ingredient__c> example2 = [Select Name, TestField__c FROM Ingredient__c where Name LIKE :exampleString];
        //return example2[0].TestField__c;
        Ingredient__c flavorAllergy = new Ingredient__c();
        flavorAllergy = [SELECT Ice_Cream_Flavor__r.Name, Name, Allergy__c, Pick_Ingredients__c, Calories__c, Fat_g__c, Cholesterol_mg__c, Carbs_g__c, Sugars_g__c, Protein_g__c 
                                  FROM Ingredient__c WHERE Ice_Cream_Flavor__r.Name LIKE :exampleString LIMIT 1];
        return flavorAllergy;
        
    }
}