IceCreamShop/force-app/main/default/objects/Ice_Cream_Flavor__c/Ice_Cream_Flavor__c.object-meta.xml
<CustomObject>
    <label>Ice Cream Flavor</label>
    <nameField>
        <label>Ice Cream Flavor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ice Cream Flavors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

IceCreamShop/force-app/main/default/objects/Ice_Cream_Flavor__c/fields/Current_Scoops_Removed__c.field-meta.xml
<CustomField>
    <fullName>Current_Scoops_Removed__c</fullName>
    <label>Current Scoops Removed</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

IceCreamShop/force-app/main/default/objects/Ice_Cream_Flavor__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

IceCreamShop/force-app/main/default/objects/Ice_Cream_Flavor__c/fields/Sale_Price_Per_Scoop__c.field-meta.xml
<CustomField>
    <fullName>Sale_Price_Per_Scoop__c</fullName>
    <label>Sale Price Per Scoop</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

IceCreamShop/force-app/main/default/objects/Sale__c/Sale__c.object-meta.xml
<CustomObject>
    <label>Sale</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Sale Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

IceCreamShop/force-app/main/default/objects/Sale__c/fields/Ice_Cream_Flavor__c.field-meta.xml
<CustomField>
    <fullName>Ice_Cream_Flavor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Ice Cream Flavor</label>
    <referenceTo>Ice_Cream_Flavor__c</referenceTo>
    <relationshipLabel>Sales</relationshipLabel>
    <relationshipName>Sales</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

IceCreamShop/force-app/main/default/objects/Sale__c/fields/Scoop_Number__c.field-meta.xml
<CustomField>
    <fullName>Scoop_Number__c</fullName>
    <label>Scoop Number</label>
    <precision>1</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

IceCreamShop/force-app/main/default/classes/FlavorPageTestClass.cls
@isTest
public class FlavorPageTestClass {

    @isTest
    static void testFlavorPage() {
        // Insert a flavor
        Ice_Cream_Flavor__c flavor1 = new Ice_Cream_Flavor__c();
        flavor1.Name = 'blue flavor';
        flavor1.Sale_Price_Per_Scoop__c = 3;
        flavor1.Current_Scoops_Removed__c = 0;
        flavor1.Quantity__c = 50;
        insert flavor1;
        
        // Insert another flavor
        Ice_Cream_Flavor__c flavor2 = new Ice_Cream_Flavor__c();
        flavor2.Name = 'green flavor';
        flavor2.Sale_Price_Per_Scoop__c = 2;
        flavor2.Current_Scoops_Removed__c = 0;
        flavor2.Quantity__c = 50;
        insert flavor2;
        
        // Insert some sales
        Integer i = 0;
        while (i < 5) {
            Sale__c sale = new Sale__c();
            sale.Ice_Cream_Flavor__c = flavor1.Id;
            sale.Scoop_Number__c = i + 1;
            insert sale;
            i += 1;
        }
        i = 0;
        while (i < 3) {
            Sale__c sale = new Sale__c();
            sale.Ice_Cream_Flavor__c = flavor2.Id;
            sale.Scoop_Number__c = 2;
            insert sale;
            i += 1;
        }
        
        // Create controller
        FlavorPageController controller = new FlavorPageController();
        
        // Test that the controller's allFlavors and flavorWrappers are correct
        System.assertEquals(2,controller.allFlavors.size());
        System.assertEquals(15, controller.allFlavorWrappers[0].numberSold);
        System.assertEquals(6, controller.allFlavorWrappers[1].numberSold);
        System.assertEquals('blue flavor', controller.allFlavorWrappers[0].flavor.Name);
    }
}