IceCreamShop/force-app/main/default/objects/Ice_Cream_Flavor__c/Ice_Cream_Flavor__c.object-meta.xml
<CustomObject>
    <label>Ice Cream Flavor</label>
    <nameField>
        <label>Ice Cream Flavor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ice Cream Flavors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

IceCreamShop/force-app/main/default/objects/Ingredient__c/Ingredient__c.object-meta.xml
<CustomObject>
    <label>Ingredient</label>
    <nameField>
        <displayFormat>ICN-{0}</displayFormat>
        <label>Ice Cream Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ingredients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

IceCreamShop/force-app/main/default/objects/Ingredient__c/fields/Allergy__c.field-meta.xml
<CustomField>
    <fullName>Allergy__c</fullName>
    <label>Allergy</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Milk</fullName>
            </value>
            <value>
                <fullName>Gluten</fullName>
            </value>
            <value>
                <fullName>Tree Nuts</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

IceCreamShop/force-app/main/default/objects/Ingredient__c/fields/Ice_Cream_Flavor__c.field-meta.xml
<CustomField>
    <fullName>Ice_Cream_Flavor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Ice Cream Flavor</label>
    <referenceTo>Ice_Cream_Flavor__c</referenceTo>
    <relationshipLabel>Ingredients</relationshipLabel>
    <relationshipName>Ingredients</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

IceCreamShop/force-app/main/default/objects/Ingredient__c/fields/Pick_Ingredients__c.field-meta.xml
<CustomField>
    <fullName>Pick_Ingredients__c</fullName>
    <label>Pick Ingredients</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Blueberrys</fullName>
            </value>
            <value>
                <fullName>Cookie Dough</fullName>
            </value>
            <value>
                <fullName>Cream</fullName>
            </value>
            <value>
                <fullName>Flavoring</fullName>
            </value>
            <value>
                <fullName>Ice</fullName>
            </value>
            <value>
                <fullName>Milk</fullName>
            </value>
            <value>
                <fullName>Splenda</fullName>
            </value>
            <value>
                <fullName>Strawberries</fullName>
            </value>
            <value>
                <fullName>Sugar</fullName>
            </value>
            <value>
                <fullName>Vanilla</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

IceCreamShop/force-app/main/default/classes/ControllerAllergyTest.cls
@isTest (SeeAllData=true)
public class ControllerAllergyTest 
{
    
    @isTest
    static void testController()
    {
        Ingredient__c ing = new Ingredient__c();
        ApexPages.StandardController sc = new ApexPages.StandardController(ing);

        ControllerAllergy control = new ControllerAllergy(sc);
        
        control.name = 'berry';
        
        control.flavorListClickHandlerApex();

        Ingredient__c flavorIngredients = [SELECT Ice_Cream_Flavor__r.Name, Name, Allergy__c, Pick_Ingredients__c 
        FROM Ingredient__c WHERE Ice_Cream_Flavor__r.Name LIKE 'berry' LIMIT 1];

        System.assertEquals(flavorIngredients, control.flavorIngredients);

        System.assertequals([SELECT Id, Name FROM Ice_Cream_Flavor__c ], control.flavorList); //else
        System.assertequals([SELECT Id, Name FROM Ice_Cream_Flavor__c ], control.flavorList); //if
    }
}    