IceCreamShop/force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <label>Job Application</label>
    <nameField>
        <displayFormat>Applicant-{0000}</displayFormat>
        <label>Job Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

IceCreamShop/force-app/main/default/objects/Job_Application__c/fields/Education_Level__c.field-meta.xml
<CustomField>
    <fullName>Education_Level__c</fullName>
    <label>Education Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Less than High School or Equivalent</fullName>
            </value>
            <value>
                <fullName>High School Diploma or GED</fullName>
            </value>
            <value>
                <fullName>Some College</fullName>
            </value>
            <value>
                <fullName>Associates Degree</fullName>
            </value>
            <value>
                <fullName>Bachelors Degree</fullName>
            </value>
            <value>
                <fullName>Master&apos;s Degree</fullName>
            </value>
            <value>
                <fullName>PhD</fullName>
            </value>
            <value>
                <fullName>Trade School</fullName>
            </value>
            <value>
                <fullName>Medical School</fullName>
            </value>
            <value>
                <fullName>Law School</fullName>
            </value>
            <value>
                <fullName>Other Post-Secondary education</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

IceCreamShop/force-app/main/default/objects/Job_Application__c/fields/Graduated__c.field-meta.xml
<CustomField>
    <fullName>Graduated__c</fullName>
    <label>Graduated</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

IceCreamShop/force-app/main/default/objects/Job_Application__c/fields/Graduation_Date_if_applicable__c.field-meta.xml
<CustomField>
    <fullName>Graduation_Date_if_applicable__c</fullName>
    <label>Graduation Date (if applicable)</label>
    <type>Date</type>
</CustomField>

IceCreamShop/force-app/main/default/objects/Job_Application__c/fields/Job_Listing__c.field-meta.xml
<CustomField>
    <fullName>Job_Listing__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job Listing</label>
    <referenceTo>Job_Listing__c</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

IceCreamShop/force-app/main/default/objects/Job_Application__c/fields/Major_if_applicable__c.field-meta.xml
<CustomField>
    <fullName>Major_if_applicable__c</fullName>
    <label>Major (if applicable)</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

IceCreamShop/force-app/main/default/objects/Job_Application__c/fields/Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Phone_Number__c</fullName>
    <externalId>true</externalId>
    <label>Phone Number</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

IceCreamShop/force-app/main/default/objects/Job_Application__c/fields/Second_Language_if_applicable__c.field-meta.xml
<CustomField>
    <fullName>Second_Language_if_applicable__c</fullName>
    <label>Second Language (if applicable</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

IceCreamShop/force-app/main/default/objects/Job_Application__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>IIA</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>NV</fullName>
            </value>
            <value>
                <fullName>NH</fullName>
            </value>
            <value>
                <fullName>NJ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

IceCreamShop/force-app/main/default/objects/Job_Listing__c/Job_Listing__c.object-meta.xml
<CustomObject>
    <label>Job Listing</label>
    <nameField>
        <label>Job Listing</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Listings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

IceCreamShop/force-app/main/default/objects/Job_Listing__c/fields/More_Info__c.field-meta.xml
<CustomField>
    <fullName>More_Info__c</fullName>
    <label>More Info</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

IceCreamShop/force-app/main/default/classes/JobAppApexController.cls
public class JobAppApexController {
    
    @AuraEnabled
    public static String createJobAppRecord(String firstName, String lastName, Date graduationDate,
                                            String schoolName, String address, String address2,
                                            String city, String email, String phone,
                                            String secondLanguage, String major, String zip,
                                           String state, String educationLevel, String graduated, Job_Listing__c listing) {
                                                
                                                try {
                                                    Job_Application__c jobApp = new Job_Application__c();
                                                    jobApp.First_Name__c = firstName;
                                                    jobApp.Last_Name__c = lastName;
                                                    jobApp.Graduation_Date_if_applicable__c = graduationDate;
                                                    jobApp.School_Name__c = schoolName;
                                                    jobApp.Address__c = address;
                                                    jobApp.Address_Line_2__c = address2;
                                                    jobApp.City__c = city;
                                                    jobApp.Email__c = email;
                                                    jobApp.Phone_Number__c = phone;
                                                    jobApp.Second_Language_if_applicable__c = secondLanguage;
                                                    jobApp.Major_if_applicable__c = major;
                                                    jobApp.Zip_Code__c = zip;
                                                    jobApp.State__c = state;
                                                    jobApp.Education_Level__c = educationLevel;
                                                    jobApp.Graduated__c = graduated;
                                                    jobApp.Job_Listing__c = listing.Id;
                                                    insert jobApp;
                                                } catch (DMLException e) {
                                                    if (e.getNumDml() > 0) {
                                                        return 'Error: ' + e.getDmlMessage(0);
                                                    }
                                                    return 'Unknown error; please try again.';
                                                }
                                                return 'Success';
                                            }
    
    @AuraEnabled 
    public static Map<String, String> getStatePicklistValues(){
        List<Schema.PicklistEntry> picklistEntries = Job_Application__c.State__c.getDescribe().getPicklistValues();
        return JobAppApexController.picklistEntriesToMap(picklistEntries);
    }
    
    @AuraEnabled 
    public static Map<String, String> getEducationLevelPicklistValues(){
        List<Schema.PicklistEntry> picklistEntries = Job_Application__c.Education_Level__c.getDescribe().getPicklistValues();
        return JobAppApexController.picklistEntriesToMap(picklistEntries);
    }
    
    @AuraEnabled 
    public static Map<String, String> getGraduatedPicklistValues(){
        List<Schema.PicklistEntry> picklistEntries = Job_Application__c.Graduated__c.getDescribe().getPicklistValues();
        return JobAppApexController.picklistEntriesToMap(picklistEntries);
    }
    
    public static Map<String,String> picklistEntriesToMap(List<Schema.PicklistEntry> picklistEntries) {
        Map<String, String> options = new Map<String, String>();
        for (Schema.PicklistEntry p: picklistEntries) {
            options.put(p.getValue(), p.getLabel());
        }
        return options;
    }
    
    @AuraEnabled
    public static List<Job_Listing__c> getJobListings() {
        return [SELECT Name, More_Info__c FROM Job_Listing__c];
    }
}