IceCreamShop/force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <label>Job Application</label>
    <nameField>
        <displayFormat>Applicant-{0000}</displayFormat>
        <label>Job Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

IceCreamShop/force-app/main/default/objects/Job_Application__c/fields/Job_Listing__c.field-meta.xml
<CustomField>
    <fullName>Job_Listing__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job Listing</label>
    <referenceTo>Job_Listing__c</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

IceCreamShop/force-app/main/default/objects/Job_Application__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>IIA</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>NV</fullName>
            </value>
            <value>
                <fullName>NH</fullName>
            </value>
            <value>
                <fullName>NJ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

IceCreamShop/force-app/main/default/objects/Job_Listing__c/Job_Listing__c.object-meta.xml
<CustomObject>
    <label>Job Listing</label>
    <nameField>
        <label>Job Listing</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Listings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

IceCreamShop/force-app/main/default/objects/Job_Listing__c/fields/More_Info__c.field-meta.xml
<CustomField>
    <fullName>More_Info__c</fullName>
    <label>More Info</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

IceCreamShop/force-app/main/default/classes/ApplicationController.cls
public class ApplicationController  {
    
    
    
    public static List <Job_Listing__c> JobList 
    {
        get 
        {
            if (JobList != null)
            {
                return JobList;
            }
            else
            {
                JobList = [SELECT Id, Name, More_Info__c FROM Job_Listing__c ];
                return JobList;
            }
            
        }
        set;
    }

    public String name {get; set;}
    public static Integer rowIndex {get; set;}
   // public Job_Listing__c moreIndex = JobList[rowIndex];
    public String moreInfo {get; set;}

    
    
  
    
    public string jobId{get;set;}
    public string jobName{get;set;}
    
    public void JobListClickHandlerApex(){
        this.jobId = JobList[rowIndex -1].Id;
        this.jobName = JobList[rowIndex -1].Name;
        moreInfo = JobList[rowIndex -1].More_Info__c;
        //jobId = JobList[rowIndex -1].Id;
        //String name = ApexPages.currentPage().getParameters().get('textName');

       // System.debug(name+ '   '  +rowIndex);

       // this.moreInfo = [SELECT Name FROM Job_Listing__c Where Name =: name LIMIT 1];
        //System.debug(flavorIngredients.name);
    }
   /* public static String sendId(){
        //jobId = JobList[rowIndex -1].Id;
        return jobId;
    }*/
     
    public PageReference application(){
       	
        return Page.JobApplication;
    }
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
 //   public string appJobId {get;set;}
  //  public virtual void changeId(string id){
    //    jobId = id;
    //}
	public ApplicationController(){
        this.jobApp = new Job_Application__c();
      //  appJobId = sendId(); 
        
    }
   // public ApplicationController(ApexPages.StandardController controller){}
    
    //public String test3{get;set;}
    

    
    public List<SelectOption> State {get{
        List<Schema.PicklistEntry> appState = Schema.SObjectType.Job_Application__c.Fields.State__c.getPicklistValues();
        State = new List<SelectOption>();
        for(Schema.PicklistEntry tempState: appState){
            State.add(new SelectOption(tempState.getValue(), tempState.getLabel()));
        }
        return State;
    } set;}

    
    
    
   // public String applicantFirstName {get;set;}
    //public String applicantLastName {get;set;}
    //public Integer i = 2;
    
  // public String applicantAddress{get;set;}
  //  public String applicantAddress2{get;set;}
   // Public String applicantCity{get;set;}
//    Public String applicantZip{get;set;}
    
   // public String appFullName = applicantFirstName + applicantLastName;
   
  /*  public void testingMethod(){
        System.debug('hi');
        jobApp.First_Name__c = appFullName;
        
    }*/
    
   
    
    
    
    
    
    
    
    
    public Job_Application__c jobApp { get; set; }
    

    
  
    
    
    //   public Job_Application__c jobApp = new Job_Application__c();
  //   jobApp.State__c = State;
  //   jobApp.First_Name__c = applicantFirstName;
    public PageReference submitApp(){
        jobApp.Job_Listing__c = jobId;
        insert this.jobApp;

        return Page.SubmitPage;
        
    }
    

}